sudo: required
language: python
services:
  - docker

script:
  - ./quickstart.sh

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
  - chmod +x /usr/local/bin/ecs-cli
  - ecs-cli up --region us-west-2 --cluster rooseveit-site --capability-iam
